repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: py-compile
        name: py-compile
        entry: python3 -B -m py_compile
        language: system
        types: [python]
        pass_filenames: true
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        args: [--markdown-linebreak-ext=md]
