"""Route tables for the local HTTP API.

Both dispatchers were extracted from Handler._do_GET/_do_POST chains. The
handler methods live on web_app.Handler; these tables map a request path to
the method name that serves it. Adding a route = add a handler method and one
table entry here.
"""

from api_errors import RouteNotFound


GET_TABLE = {
    "/": "_api_get_index",
    "/api/backup": "_api_get_api_backup",
    "/api/backup/manifest": "_api_get_api_backup_manifest",
    "/api/backups": "_api_get_api_backups",
    "/api/discovery": "_api_get_api_discovery",
    "/api/document": "_api_get_api_document",
    "/api/emulators": "_api_get_api_emulators",
    "/api/emulators/definitions": "_api_get_api_emulators_definitions",
    "/api/emulators/dependencies": "_api_get_api_emulators_dependencies",
    "/api/emulators/recommend": "_api_get_api_emulators_recommend",
    "/api/emulators/scan-configs": "_api_get_api_emulators_scan_configs",
    "/api/explorer/facets": "_api_get_api_explorer_facets",
    "/api/filter-presets": "_api_get_api_filter_presets",
    "/api/gameyfin/install/status": "_api_get_api_gameyfin_install_status",
    "/api/gameyfin/providers": "_api_get_api_gameyfin_providers",
    "/api/highscores": "_api_get_api_highscores",
    "/api/history": "_api_get_api_history",
    "/api/jobs": "_api_get_api_jobs",
    "/api/import/exclusions": "_api_get_api_import_exclusions",
    "/api/launcher/menu": "_api_get_api_launcher_menu",
    "/api/library": "_api_get_api_library",
    "/api/log": "_api_get_api_log",
    "/api/media": "_api_get_api_media",
    "/api/media/audit": "_api_get_api_media_audit",
    "/api/media/bulk/status": "_api_get_api_media_bulk_status",
    "/api/media/duplicates": "_api_get_api_media_duplicates",
    "/api/media/queue": "_api_get_api_media_queue",
    "/api/metadata/igdb/search": "_api_get_api_metadata_igdb_search",
    "/api/metadata/search": "_api_get_api_metadata_search",
    "/api/metadata/status": "_api_get_api_metadata_status",
    "/api/notifications": "_api_get_api_notifications",
    "/api/obs/status": "_api_get_api_obs_status",
    "/api/perf_profiles": "_api_get_api_perf_profiles",
    "/api/platform/document": "_api_get_api_platform_document",
    "/api/platform/documents": "_api_get_api_platform_documents",
    "/api/plugins": "_api_get_api_plugins",
    "/api/plugins/catalog": "_api_get_api_plugins_catalog",
    "/api/premium/media-packs": "_api_get_api_premium_media_packs",
    "/api/premium/platform-categories": "_api_get_api_premium_platform_categories",
    "/api/premium/strings": "_api_get_api_premium_strings",
    "/api/profiles": "_api_get_api_profiles",
    "/api/queue": "_api_get_api_queue",
    "/api/ra/badge": "_api_get_api_ra_badge",
    "/api/ra/settings": "_api_get_api_ra_settings",
    "/api/related": "_api_get_api_related",
    "/api/related/rich": "_api_get_api_related_rich",
    "/api/running": "_api_get_api_running",
    "/api/save-tools/status": "_api_get_api_save_tools_status",
    "/api/saves": "_api_get_api_saves",
    "/api/saves/discover": "_api_get_api_saves_discover",
    "/api/saves/scan": "_api_get_api_saves_scan",
    "/api/settings": "_api_get_api_settings",
    "/api/storefront/catalog": "_api_get_api_storefront_catalog",
    "/api/tags": "_api_get_api_tags",
    "/api/theme.css": "_api_get_api_theme_css",
    "/api/themes": "_api_get_api_themes",
    "/api/update": "_api_get_api_update",
    "/api/webhooks": "_api_get_api_webhooks",
    "/favicon.ico": "_api_get_favicon",
    "/favicon.svg": "_api_get_favicon",
    "/index.html": "_api_get_index",
}

POST_TABLE = {
    "/api/backup/create": "_api_post_api_backup_create",
    "/api/backup/restore": "_api_post_api_backup_restore",
    "/api/bezels/download": "_api_post_api_bezels_download",
    "/api/bigbox/mode": "_api_post_api_bigbox_mode",
    "/api/cloud/sync": "_api_post_api_cloud_sync",
    "/api/desktop/install": "_api_post_api_desktop_install",
    "/api/emulators/install": "_api_post_api_emulators_install",
    "/api/emulators/install-all": "_api_post_api_emulators_install_all",
    "/api/emulators/open": "_api_post_api_emulators_open",
    "/api/emulators/scan": "_api_post_api_emulators_scan",
    "/api/emulators/scan-configs": "_api_post_api_emulators_scan_configs",
    "/api/emulators/update": "_api_post_api_emulators_update",
    "/api/emulators/update-all": "_api_post_api_emulators_update_all",
    "/api/emumovies/download": "_api_post_api_emumovies_download",
    "/api/emumovies/settings": "_api_post_api_emumovies_settings",
    "/api/extra/launch": "_api_post_api_extra_launch",
    "/api/favorite": "_api_post_api_favorite",
    "/api/filter-presets": "_api_post_api_filter_presets",
    "/api/filter-presets/delete": "_api_post_api_filter_presets_delete",
    "/api/game": "_api_post_api_game",
    "/api/game/delete": "_api_post_api_game_delete",
    "/api/games/bulk": "_api_post_api_games_bulk",
    "/api/games/bulk-wizard": "_api_post_api_games_bulk_wizard",
    "/api/games/delete-steam": "_api_post_api_games_delete_steam",
    "/api/gameyfin/install": "_api_post_api_gameyfin_install",
    "/api/gameyfin/test": "_api_post_api_gameyfin_test",
    "/api/gameyfin/uninstall": "_api_post_api_gameyfin_uninstall",
    "/api/health": "_api_post_api_health",
    "/api/health/dedupe": "_api_post_api_health_dedupe",
    "/api/highscores/export": "_api_post_api_highscores_export",
    "/api/highscores/import": "_api_post_api_highscores_import",
    "/api/image-group": "_api_post_api_image_group",
    "/api/import": "_api_post_api_import",
    "/api/import/arcade": "_api_post_api_import_arcade",
    "/api/import/exclusions": "_api_post_api_import_exclusions",
    "/api/import/exclusions/delete": "_api_post_api_import_exclusions_delete",
    "/api/import/heroic": "_api_post_api_import_heroic",
    "/api/import/loose-arcade": "_api_post_api_import_loose_arcade",
    "/api/import/lutris": "_api_post_api_import_lutris",
    "/api/import/rpcs3": "_api_post_api_import_rpcs3",
    "/api/import/scummvm": "_api_post_api_import_scummvm",
    "/api/import/steam": "_api_post_api_import_steam",
    "/api/import/vita3k": "_api_post_api_import_vita3k",
    "/api/import/watch": "_api_post_api_import_watch",
    "/api/import/wizard": "_api_post_api_import_wizard",
    "/api/import/xbox360": "_api_post_api_import_xbox360",
    "/api/launch": "_api_post_api_launch",
    "/api/media/bulk": "_api_post_api_media_bulk",
    "/api/media/cleanup": "_api_post_api_media_cleanup",
    "/api/metadata/apply": "_api_post_api_metadata_apply",
    "/api/metadata/gog": "_api_post_api_metadata_gog",
    "/api/metadata/igdb/apply": "_api_post_api_metadata_igdb_apply",
    "/api/metadata/steam": "_api_post_api_metadata_steam",
    "/api/metadata/sync": "_api_post_api_metadata_sync",
    "/api/metadata/trailer": "_api_post_api_metadata_trailer",
    "/api/notifications": "_api_post_api_notifications",
    "/api/obs/attach": "_api_post_api_obs_attach",
    "/api/perf_profiles": "_api_post_api_perf_profiles",
    "/api/platform/documents": "_api_post_api_platform_documents",
    "/api/playlists": "_api_post_api_playlists",
    "/api/playlists/delete": "_api_post_api_playlists_delete",
    "/api/plugins/catalog/install": "_api_post_api_plugins_catalog_install",
    "/api/plugins/install": "_api_post_api_plugins_install",
    "/api/plugins/remove": "_api_post_api_plugins_remove",
    "/api/plugins/toggle": "_api_post_api_plugins_toggle",
    "/api/premium/media-packs/apply": "_api_post_api_premium_media_packs_apply",
    "/api/profiles": "_api_post_api_profiles",
    "/api/queue": "_api_post_api_queue",
    "/api/ra/game": "_api_post_api_ra_game",
    "/api/ra/inject": "_api_post_api_ra_inject",
    "/api/ra/settings": "_api_post_api_ra_settings",
    "/api/save-tools/hoard": "_api_post_api_save_tools_hoard",
    "/api/save-tools/ludusavi": "_api_post_api_save_tools_ludusavi",
    "/api/saves/add": "_api_post_api_saves_add",
    "/api/saves/backup": "_api_post_api_saves_backup",
    "/api/saves/restore": "_api_post_api_saves_restore",
    "/api/saves/scan/apply": "_api_post_api_saves_scan_apply",
    "/api/screenshot": "_api_post_api_screenshot",
    "/api/session/control": "_api_post_api_session_control",
    "/api/settings": "_api_post_api_settings",
    "/api/shutdown": "_api_post_api_shutdown",
    "/api/state/recover": "_api_post_api_state_recover",
    "/api/storefront/import": "_api_post_api_storefront_import",
    "/api/tags": "_api_post_api_tags",
    "/api/themes/import": "_api_post_api_themes_import",
    "/api/themes/open-folder": "_api_post_api_themes_open_folder",
    "/api/themes/select": "_api_post_api_themes_select",
    "/api/update/install": "_api_post_api_update_install",
    "/api/webhooks": "_api_post_api_webhooks",
    "/api/webhooks/test": "_api_post_api_webhooks_test",
}


def dispatch_get(handler, parsed):
    method = GET_TABLE.get(parsed.path)
    if method is None:
        raise RouteNotFound("Not found")
    getattr(handler, method)(parsed)


def dispatch_post(handler, route, payload):
    method = POST_TABLE.get(route)
    if method is None:
        raise RouteNotFound("Not found")
    getattr(handler, method)(payload)
