#!/usr/bin/env python3
"""Ratchet the persisted settings schema so a user's saved preferences survive.

``settings_schema.KNOWN_SETTINGS`` is a destructive allowlist:
``sanitize_settings`` drops every key that is not in it, and
``prune_unknown_settings`` deletes those keys from stored state. Deleting one
line from that set therefore does not just remove a feature, it **erases the
setting from every existing library on the next save** -- the user's theme
choice, their controller map, their webhook list, their backup schedule. No
test fails, because the write path is behaving exactly as written.

This gate makes that a deliberate act:

- A key present in ``scripts/contracts/settings.json`` that disappears from
  ``KNOWN_SETTINGS`` is a FAILURE.
- The baseline is itself ratcheted against ``HEAD``, so deleting the key from
  the baseline to hide the removal is also a failure.
- A key may only leave by moving to the ``retired`` list with a written reason,
  and because the runtime prunes on save, retiring a key that holds persisted
  user data additionally requires naming the migration that preserves it.

Run directly:  python3 -B scripts/check_settings_contract.py
Regenerate:   python3 -B scripts/check_settings_contract.py --update

See ADR 0060.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

BASELINE = ROOT / "scripts" / "contracts" / "settings.json"

# Keys whose stored value is user data the runtime would silently destroy if
# the key were dropped. Retiring one requires a data-preservation note.
USER_DATA_KEYS = frozenset({
    "theme", "theme_by_platform", "controller_map", "controller_prompt_pack",
    "gamescope_preset", "gamescope_custom_presets", "webhooks", "backup_auto_enabled",
    "backup_auto_keep", "cloud_folder", "library_sync_enabled", "filter_presets",
    "watch_folders", "emulator_scan_configs", "import_exclusions", "platform_categories",
    "custom_field_defs", "startup_commands", "shutdown_commands", "bigbox_shutdown_commands",
    "party_queue", "museum_kiosk_pin_hash", "household_stats_sharing", "locale",
    "library_music", "active_media_packs", "memories_import_roots", "obs_recording_path",
})


def live_keys() -> set[str]:
    """Return the live KNOWN_SETTINGS keys, read from the real module."""
    from settings_schema import KNOWN_SETTINGS

    return set(KNOWN_SETTINGS)


def _parse(data: dict) -> tuple[list[str], dict[str, str]]:
    keys = sorted(data.get("keys", []))
    retired = {entry["key"]: entry.get("reason", "") for entry in data.get("retired", [])}
    return keys, retired


def load_baseline() -> dict | None:
    if not BASELINE.is_file():
        return None
    try:
        return json.loads(BASELINE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"FAIL: {BASELINE.relative_to(ROOT)} is not valid JSON: {exc}")
        raise SystemExit(1) from exc


def committed_baseline() -> dict | None:
    """Return the baseline as committed in HEAD, or None when unavailable."""
    try:
        result = subprocess.run(
            ["git", "show", "HEAD:scripts/contracts/settings.json"],
            cwd=ROOT, capture_output=True, text=True, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0 or not result.stdout.strip():
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def write_baseline(live: set[str], retired: dict[str, str] | None = None) -> None:
    payload = {
        "version": 1,
        "note": "Generated by scripts/check_settings_contract.py --update. KNOWN_SETTINGS is a "
        "destructive allowlist: removing a key erases it from every user's stored state on "
        "the next save. Keys may be added freely; removing one fails the gate and requires a "
        "retired entry naming the migration. See ADR 0060.",
        "keys": sorted(live),
        "retired": [
            {"key": key, "reason": reason} for key, reason in sorted((retired or {}).items())
        ],
    }
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    live = live_keys()
    data = load_baseline()
    if data is None:
        print(f"FAIL: {BASELINE.relative_to(ROOT)} is missing. Generate it with:")
        print("  python3 -B scripts/check_settings_contract.py --update")
        return 1

    baseline_keys, retired = _parse(data)
    baseline = set(baseline_keys)
    failures: list[str] = []

    # Layer 1: the live schema must not lose anything the baseline promises.
    for key in sorted(baseline):
        if key not in live:
            failures.append(f"REMOVED {key} (stored state for this key would be pruned)")

    # Layer 2: the baseline is ratcheted against itself.
    committed = committed_baseline()
    if committed is None:
        print("settings contract: git unavailable, baseline-vs-git ratchet skipped")
    else:
        committed_keys, committed_retired = _parse(committed)
        for key in sorted(set(committed_keys) - baseline):
            if key not in retired:
                failures.append(
                    f"BASELINE-SHRINK {key} was dropped from settings.json without a retired entry"
                )
        for key, reason in sorted(retired.items()):
            if not str(reason).strip():
                failures.append(f"RETIRED-NO-REASON {key} has an empty reason")
            if key in baseline:
                failures.append(f"RETIRED-STILL-LIVE {key} is in both keys and retired")
            if key not in set(committed_keys) and key not in committed_retired:
                failures.append(f"RETIRED-FABRICATED {key} was never in the committed baseline")
            if key in USER_DATA_KEYS and "migrat" not in str(reason).lower():
                failures.append(
                    f"RETIRED-USER-DATA {key} holds persisted user data; the reason must name "
                    f"the migration that preserves it (include the word 'migration')"
                )
        for key in sorted(committed_retired):
            if key not in retired:
                failures.append(f"RETIRED-REMOVED {key} was deleted from the retired ledger")
            elif committed_retired[key] != retired[key]:
                failures.append(f"RETIRED-REWRITTEN {key}: the recorded reason was changed")

    if failures:
        print(f"FAIL: settings schema regressed ({len(failures)} problem(s)):")
        for line in failures:
            print(f"  {line}")
        print("")
        print("KNOWN_SETTINGS is a destructive allowlist. Dropping a key erases it from every")
        print("user's stored state on the next save. If removal is intentional, move the key")
        print("to the retired list with a reason in the SAME commit, ship the migration that")
        print("preserves existing values, and record it in the changelog.")
        return 1

    added = sorted(live - baseline)
    if added:
        print(f"settings contract: {len(added)} new key(s) not yet baselined: {added}")
        print("Run: python3 -B scripts/check_settings_contract.py --update")

    print(
        f"settings contract OK: {len(live)} live, {len(baseline)} baselined, "
        f"{len(retired)} retired, 0 regressions"
    )
    return 0


if __name__ == "__main__":
    if "--update" in sys.argv:
        existing = load_baseline() or {}
        write_baseline(live_keys(), _parse(existing)[1])
        print(f"Wrote {BASELINE.relative_to(ROOT)}")
        raise SystemExit(0)
    raise SystemExit(main())
