#!/usr/bin/env python3
"""Ratchet the full HTTP route surface so a feature cannot disappear silently.

The v1 contract (``v1_contracts.json``) freezes the 61 routes the native host
depends on. That leaves the other 213 routes unprotected: every ``/api/v2/*``
feature added since 1.9 and every unversioned ``/api/*`` route can be deleted,
renamed, or have its HTTP method changed in a single commit, and no gate
notices. The frontend then calls a 404 at runtime, in a browser, on a user's
machine, where nothing is watching.

This gate closes that hole with a **ratchet** in two layers, because a
one-layer ratchet is trivially bypassed by shrinking its own baseline:

**Layer 1 - code against baseline.** A route recorded in
``scripts/contracts/routes.json`` that disappears, is renamed, or loses/gains an
HTTP method is a FAILURE.

**Layer 2 - baseline against git.** The baseline itself is ratcheted against
the copy committed in ``HEAD``. Deleting entries from the JSON to hide a
removal is itself a failure, which is the only way layer 1 can be defeated. A
route may only leave the baseline by being moved to the ``retired`` list with a
non-empty ``reason``, and the retired list may only grow.

So the surface may grow freely, and shrink only through a written, reviewable,
permanent record of what was removed and why. See ADR 0060.

Run directly:  python3 -B scripts/check_routes_contract.py
Regenerate:   python3 -B scripts/check_routes_contract.py --update
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import contract_ratchet  # noqa: E402  (scripts/ is not a package)

BASELINE = ROOT / "scripts" / "contracts" / "routes.json"

# Static file serving and the token handshake are answered by the server but are
# not part of the feature surface, so they stay out of the baseline.
IGNORED_PREFIXES = ("/static/", "/assets/", "/favicon")


def live_routes() -> dict[str, list[str]]:
    """Return path -> sorted methods for every registered route.

    Imports the registry rather than parsing source, so the baseline reflects
    what the server actually dispatches, including multi-path decorators and
    the v1 alias expansion.
    """
    from routes.registry import all_routes

    surface: dict[str, set[str]] = {}
    for route in all_routes():
        if any(route.path.startswith(prefix) for prefix in IGNORED_PREFIXES):
            continue
        surface.setdefault(route.path, set()).add(route.method)
    return {path: sorted(methods) for path, methods in sorted(surface.items())}


def _parse(data: dict) -> tuple[dict[str, list[str]], dict[str, str]]:
    routes = {entry["path"]: sorted(entry["methods"]) for entry in data.get("routes", [])}
    retired = {entry["path"]: entry.get("reason", "") for entry in data.get("retired", [])}
    return routes, retired


def load_baseline() -> dict | None:
    if not BASELINE.is_file():
        return None
    try:
        return json.loads(BASELINE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"FAIL: {BASELINE.relative_to(ROOT)} is not valid JSON: {exc}")
        raise SystemExit(1) from exc


def write_baseline(live: dict[str, list[str]], retired: dict[str, str] | None = None) -> None:
    payload = {
        "version": 1,
        "note": "Generated by scripts/check_routes_contract.py --update. Routes may be "
        "added freely; removing or re-mapping one fails the gate, and the baseline is "
        "itself ratcheted against git, so entries may only leave via the retired list "
        "with a reason. See ADR 0060.",
        "routes": [{"methods": methods, "path": path} for path, methods in sorted(live.items())],
        "retired": [
            {"path": path, "reason": reason} for path, reason in sorted((retired or {}).items())
        ],
    }
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    live = live_routes()
    data = load_baseline()
    if data is None:
        print(f"FAIL: {BASELINE.relative_to(ROOT)} is missing. Generate it with:")
        print("  python3 -B scripts/check_routes_contract.py --update")
        return 1

    baseline, retired = _parse(data)
    failures: list[str] = []

    # Layer 1: live code must not lose anything the baseline promises.
    for path in sorted(baseline):
        if path not in live:
            failures.append(f"REMOVED {path} {baseline[path]}")
        elif baseline[path] != live[path]:
            failures.append(f"CHANGED {path}: {baseline[path]} -> {live[path]}")

    # Ledger hygiene holds even where no reference commit is available.
    failures.extend(contract_ratchet.ledger_consistency(baseline, retired))

    # Layer 2: the baseline may only shrink into the documented retired list.
    reference, reference_label = contract_ratchet.reference_data("routes.json")
    if reference is None:
        print(f"routes contract: layer 2 skipped - {reference_label}")
    else:
        ref_routes, ref_retired = _parse(reference)
        failures.extend(
            contract_ratchet.ledger_failures(
                ref_routes,
                ref_retired,
                baseline,
                retired,
                noun="route",
                drop_reason="was dropped from routes.json and is not in the retired ledger;",
                drop_remedy='add {"path": "{key}", "reason": "..."} to the retired list',
            )
        )

    if failures:
        print(f"FAIL: HTTP route surface regressed ({len(failures)} problem(s)):")
        for line in failures:
            print(f"  {line}")
        print("")
        print("A removed or re-mapped route is a user-visible feature loss. If the")
        print("removal is intentional, move the entry to the retired list with a reason")
        print("in the SAME commit and say so in the changelog, so it is reviewed.")
        return 1

    added = sorted(set(live) - set(baseline))
    if added:
        print(f"routes contract: {len(added)} new route(s) not yet in the baseline:")
        for path in added:
            print(f"  + {path} {live[path]}")
        print("Run: python3 -B scripts/check_routes_contract.py --update")

    print(
        f"routes contract OK: {len(live)} live, {len(baseline)} baselined, "
        f"{len(retired)} retired, 0 regressions ({reference_label})"
    )
    return 0


if __name__ == "__main__":
    if "--update" in sys.argv:
        existing = load_baseline() or {}
        write_baseline(live_routes(), _parse(existing)[1])
        print(f"Wrote {BASELINE.relative_to(ROOT)}")
        raise SystemExit(0)
    raise SystemExit(main())

