#!/usr/bin/env python3
"""Verify the frontend module graph is intact and the shipped set cannot shrink.

The UI is 35 ES modules loaded from ``index.html``. Two failure modes are
invisible to the Python test suite and to eslint's local reasoning:

1. **A dangling import.** ``static/foo.js`` imports ``./bar.js`` and ``bar.js``
   is deleted or renamed. eslint may not resolve the specifier, and the page
   only breaks at runtime, in a browser, with a module error that leaves the
   whole app dead.
2. **An orphaned module.** A feature module stops being imported by anything,
   so its UI silently stops existing while the file lingers in the repo and in
   the release tarball. Nothing fails; the feature is just gone.

This gate resolves every relative ``import ... from './x.js'`` against the real
filesystem, requires ``index.html`` to reference the entry module, and ratchets
the set of shipped modules against git so one cannot quietly disappear from the
release.

Run directly:  python3 -B scripts/check_frontend_modules.py
See ADR 0049.
"""




from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

STATIC = ROOT / "static"
INDEX = ROOT / "index.html"
BASELINE = ROOT / "scripts" / "contracts" / "frontend_modules.json"

# ES module imports of a sibling file, with or without an extension.
IMPORT_RE = re.compile(r"""(?:^|\s)(?:import|export)[^'"]*from\s*['"]\./([A-Za-z0-9_.\-]+)['"]""")
BARE_IMPORT_RE = re.compile(r"""(?:^|\s)import\s*['"]\./([A-Za-z0-9_.\-]+)['"]""")
# The search worker is loaded by the worker constructor, not by app.js.
WORKER_MODULES = {"worker.search.js"}
# The entry module is referenced from index.html as a classic script.
ENTRY_MODULES = {"app.js"}


def shipped_modules() -> set[str]:
    if not STATIC.is_dir():
        return set()
    return {path.name for path in STATIC.glob("*.js")}


def resolve(specifier: str) -> str | None:
    """Resolve a relative import to a file that must exist on disk."""
    candidate = STATIC / specifier
    if candidate.suffix == ".js" and candidate.is_file():
        return specifier
    for suffix in (".js", ".mjs"):
        alt = STATIC / f"{specifier}{suffix}"
        if alt.is_file():
            return alt.name
    return None


def check_graph() -> list[str]:
    """Return every dangling-import, orphan, and entry-point problem."""
    problems: list[str] = []
    modules = shipped_modules()
    importers: dict[str, set[str]] = {name: set() for name in modules}

    for path in sorted(STATIC.glob("*.js")):
        text = path.read_text(encoding="utf-8")
        for specifier in set(IMPORT_RE.findall(text)) | set(BARE_IMPORT_RE.findall(text)):
            target = resolve(specifier)
            if target is None:
                problems.append(
                    f"{path.name}: imports './{specifier}' which does not exist "
                    f"(a dangling import breaks the whole page at runtime)"
                )
                continue
            importers.setdefault(target, set()).add(path.name)

    index_text = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
    for entry in sorted(ENTRY_MODULES):
        if entry not in index_text:
            problems.append(f"index.html does not reference the entry module {entry}")

    for module in sorted(modules):
        if module in ENTRY_MODULES or module in WORKER_MODULES:
            continue
        if not importers.get(module):
            problems.append(
                f"{module} is not imported by anything (orphaned module: its feature is "
                f"unreachable even though the file still ships)"
            )
    return problems


def committed_baseline() -> dict | None:
    """Return the contract as committed in HEAD, or None when unavailable."""
    try:
        result = subprocess.run(
            ["git", "show", "HEAD:scripts/contracts/frontend_modules.json"],
            cwd=ROOT, capture_output=True, text=True, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0 or not result.stdout.strip():
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def write_baseline(modules: set[str], retired: dict[str, str] | None = None) -> None:
    payload = {
        "version": 1,
        "note": "Generated by scripts/check_frontend_modules.py --update. Modules may be added "
        "freely; removing one fails the gate. See ADR 0049.",
        "modules": sorted(modules),
        "retired": [
            {"module": name, "reason": reason} for name, reason in sorted((retired or {}).items())
        ],
    }
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    modules = shipped_modules()
    failures = check_graph()
    retired: dict[str, str] = {}

    if not BASELINE.is_file():
        failures.append(f"{BASELINE.relative_to(ROOT)} is missing; run with --update to create it")
    else:
        try:
            data = json.loads(BASELINE.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            failures.append(f"{BASELINE.relative_to(ROOT)} is not valid JSON: {exc}")
            data = {}
        baselined = set(data.get("modules", []))
        retired = {e["module"]: e.get("reason", "") for e in data.get("retired", [])}

        for name in sorted(baselined - modules):
            if name not in retired:
                failures.append(
                    f"REMOVED {name}: a shipped frontend module disappeared; add a retired "
                    f"entry with a reason in the SAME commit"
                )
        for name, reason in sorted(retired.items()):
            if not str(reason).strip():
                failures.append(f"RETIRED-NO-REASON {name} has an empty reason")
            if name in modules:
                failures.append(f"RETIRED-STILL-LIVE {name} is both present and retired")

        committed = committed_baseline()
        if committed is None:
            print("frontend modules: git unavailable, baseline-vs-git ratchet skipped")
        else:
            committed_modules = set(committed.get("modules", []))
            committed_retired = {e["module"]: e.get("reason", "") for e in committed.get("retired", [])}
            for name in sorted(committed_modules - baselined):
                if name not in retired:
                    failures.append(f"BASELINE-SHRINK {name} was dropped from the baseline")
            for name in sorted(committed_retired):
                if name not in retired:
                    failures.append(f"RETIRED-REMOVED {name} was deleted from the retired ledger")
                elif committed_retired[name] != retired[name]:
                    failures.append(f"RETIRED-REWRITTEN {name}: the recorded reason was changed")
            for name in sorted(retired):
                if name not in committed_modules and name not in committed_retired:
                    failures.append(f"RETIRED-FABRICATED {name} was never in the committed baseline")

    if failures:
        print(f"FAIL: frontend module graph regressed ({len(failures)} problem(s)):")
        for line in failures:
            print(f"  {line}")
        return 1

    print(
        f"frontend modules OK: {len(modules)} modules, graph resolved, "
        f"{len(retired)} retired, 0 regressions"
    )
    return 0


if __name__ == "__main__":
    if "--update" in sys.argv:
        problems = check_graph()
        if problems:
            for problem in problems:
                print(f"FAIL: {problem}")
            raise SystemExit(1)
        existing: dict[str, str] = {}
        if BASELINE.is_file():
            try:
                existing = {
                    e["module"]: e.get("reason", "")
                    for e in json.loads(BASELINE.read_text(encoding="utf-8")).get("retired", [])
                }
            except json.JSONDecodeError:
                existing = {}
        write_baseline(shipped_modules(), existing)
        print(f"Wrote {BASELINE.relative_to(ROOT)}")
        raise SystemExit(0)
    raise SystemExit(main())
