#!/usr/bin/env python3
"""Verify every emulator definition is complete and the set cannot shrink.

ADR 0048 added ``native_exe_windows`` to all 24 bundled definitions because
adapter detection, resume state, and Launch Doctor need a Windows binary name
to work on the new platform. Nothing enforced it. A 25th definition added
without that key ships, and then that emulator launches on Linux and silently
fails on Windows -- the exact regression class 1.13 was written to eliminate,
one YAML file away.

This gate makes the per-definition contract explicit and enforced:

1. Every definition carries the required keys, including the Windows
   executable name, so cross-platform launch cannot silently regress.
2. Every definition declares a ``schema_version``, so a definition update
   channel can reason about compatibility later.
3. The *set* of definitions is ratcheted: dropping a definition removes an
   emulator users can launch, so it fails the gate unless it is recorded in the
   retired ledger with a reason.

Run directly:  python3 -B scripts/check_emulator_defs.py
See ADR 0060.
"""


from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import contract_ratchet  # noqa: E402  (scripts/ is not a package)

DEFS_DIR = ROOT / "emulator_defs"
BASELINE = ROOT / "scripts" / "contracts" / "emulator_defs.json"

# Keys every definition must declare. The Windows executable name is the one
# ADR 0048 relies on; the rest are what detection, launch, and the registry
# read unconditionally.
REQUIRED_KEYS = (
    "emulator_id",
    "adapter_id",
    "label",
    "platform",
    "extensions",
    "executable_patterns",
    "native_exe",
    "native_exe_windows",
    "flatpak_app_id",
    "priority",
    "startup_args",
    "state",
    "schema_version",
    "recommended",
)

TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):")


def _strip_comment(line: str) -> str:
    """Drop a trailing ``#`` comment that is not inside quotes."""
    out, quote = [], None
    for char in line:
        if quote:
            out.append(char)
            if char == quote:
                quote = None
            continue
        if char in "\"'":
            quote = char
            out.append(char)
            continue
        if char == "#":
            break
        out.append(char)
    return "".join(out)


def top_level_keys(text: str) -> set[str]:
    """Return the top-level keys of a definition, ignoring comments.

    A deliberately small reader rather than a YAML dependency: the runtime must
    stay dependency-free and the definitions are a flat, generated-shaped
    subset. ``parity_emulator_defs._parse_yaml`` remains the runtime parser.
    """
    keys = set()
    for raw in text.splitlines():
        line = _strip_comment(raw)
        if not line.strip() or line.startswith((" ", "\t", "-")):
            continue
        match = TOP_LEVEL_KEY_RE.match(line)
        if match:
            keys.add(match.group(1))
    return keys


def inspect() -> tuple[dict[str, set[str]], list[str]]:
    """Return filename -> top-level keys for every definition, plus problems."""
    problems: list[str] = []
    found: dict[str, set[str]] = {}
    if not DEFS_DIR.is_dir():
        return {}, [f"{DEFS_DIR.name}/ directory is missing"]
    for path in sorted(DEFS_DIR.glob("*.yaml")):
        keys = top_level_keys(path.read_text(encoding="utf-8"))
        found[path.name] = keys
        missing = [key for key in REQUIRED_KEYS if key not in keys]
        if missing:
            problems.append(f"{path.name}: missing required key(s): {', '.join(missing)}")
    if not found:
        problems.append("no emulator definitions found")
    return found, problems




def write_baseline(files: dict[str, set[str]], retired: dict[str, str] | None = None) -> None:
    payload = {
        "version": 1,
        "note": "Generated by scripts/check_emulator_defs.py --update. Definitions may be "
        "added freely; removing one fails the gate. See ADR 0060.",
        "definitions": [
            {"file": name, "keys": sorted(keys)} for name, keys in sorted(files.items())
        ],
        "retired": [
            {"file": name, "reason": reason} for name, reason in sorted((retired or {}).items())
        ],
    }
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    files, failures = inspect()
    retired: dict[str, str] = {}
    baselined: dict[str, set[str]] = {}

    if not BASELINE.is_file():
        failures.append(f"{BASELINE.relative_to(ROOT)} is missing; run with --update to create it")
    else:
        try:
            data = json.loads(BASELINE.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            failures.append(f"{BASELINE.relative_to(ROOT)} is not valid JSON: {exc}")
            data = {}
        baselined = {e["file"]: set(e.get("keys", [])) for e in data.get("definitions", [])}
        retired = {e["file"]: e.get("reason", "") for e in data.get("retired", [])}

        # The set of definitions may only shrink through the retired ledger.
        baselined_names = set(baselined)
        for name in sorted(baselined_names - set(files)):
            if name not in retired:
                failures.append(
                    f"REMOVED {name}: dropping a definition removes an emulator users can launch; "
                    f"add a retired entry with a reason in the SAME commit"
                )
        # Ledger hygiene holds even where no reference commit is available.
        failures.extend(contract_ratchet.ledger_consistency(baselined_names, retired))

        # Layer 2: dropping a definition *and* its baseline entry is not a way
        # to make layer 1 quiet. Compare against a reference that predates the
        # change, since HEAD is the commit under test.
        reference, reference_label = contract_ratchet.reference_data("emulator_defs.json")
        if reference is None:
            print(f"emulator defs: layer 2 skipped - {reference_label}")
        else:
            ref_names = {e["file"] for e in reference.get("definitions", [])}
            ref_retired = {e["file"]: e.get("reason", "") for e in reference.get("retired", [])}
            failures.extend(
                contract_ratchet.ledger_failures(
                    ref_names,
                    ref_retired,
                    baselined_names,
                    retired,
                    noun="definition",
                    drop_reason="was dropped from the contract and is not in the retired ledger;",
                    drop_remedy="add a retired entry with a reason in the SAME commit",
                )
            )

    if failures:
        print(f"FAIL: emulator definitions regressed ({len(failures)} problem(s)):")
        for line in failures:
            print(f"  {line}")
        print("")
        print("Every definition must carry native_exe_windows (ADR 0048) plus the other")
        print("required keys, or that emulator launches on Linux and fails on Windows.")
        return 1

    print(
        f"emulator defs OK: {len(files)} definitions, {len(REQUIRED_KEYS)} required keys each, "
        f"{len(retired)} retired, 0 regressions ({reference_label})"
    )
    return 0


if __name__ == "__main__":
    if "--update" in sys.argv:
        found, problems = inspect()
        if problems:
            for problem in problems:
                print(f"FAIL: {problem}")
            raise SystemExit(1)
        existing: dict[str, str] = {}
        if BASELINE.is_file():
            try:
                existing = {
                    e["file"]: e.get("reason", "")
                    for e in json.loads(BASELINE.read_text(encoding="utf-8")).get("retired", [])
                }
            except json.JSONDecodeError:
                existing = {}
        write_baseline(found, existing)
        print(f"Wrote {BASELINE.relative_to(ROOT)}")
        raise SystemExit(0)
    raise SystemExit(main())
